language: go
go_import_path: github.com/Ronmi/poe-tool

install:
- go get github.com/golang/dep/cmd/dep
- go get -tags gtk_3_10 -v ./...

script:
- go test ./...
- env GOOS=windows GOARCH=386 go build -tags gtk_3_10 -v

deploy:
  provider: releases
  api_key:
    secure: DyTuBTV8idCi8DonvdCgYgEHFA8cRMp+mrDUeOy7WVgWJXXDRXgMe9RnwX7stxflFI/6lCYRvpM26lQ1AxdzII5Vsqq3SOGz4E3nF+21RzUdkDAdc723b1jnesxUBfE8qJvI43ovmdLj1ZBBrXixAyrDmpGE22aVgrSnoLdUY11w9KG5M4iSVfT+J/bbp8plQ2QF6+osRct2mBLndK7JiQQG9tXTEnnqZ7NUx3rFphV2t4wrnkxbK6OtIiinidWtu6qXpC5QKZRfmwzkXcuY04gUyVuZKbHwtAXx5WtptDRVwVqEB9KG0FB/qsmuZFKjvrzW29jXbKacz2CxmLf/dB2UJXd+gD/Tf6qsxhQEO6sapOFudpFbuzaMY2ZusCcNuVg/dbXzUlem3Hzr0WSDJz00RmgtWh8Fk3+Ic51fWq9DYYVx4Mdm+CEYy/asvTeBbjPoUzDrERQ2ErrYQIyy9loNh+El72wru7dvConDup3y9DvpUVH51z7KhjmihmsSQCwbrFSgAn43JQzNqyKxsJb3WqorjY5oqIM6ip7V1BP8/OQg93u3nOxw5ekQBVwpDClxd3Dz6XeBy9PjbCCvtZn2iZV/+DI63b0mTEULOsiH5uC2TiJgFKu1TJbcj3Dgz90a3PhDsILpnPprRMsCWBmaLghUHnBK3WYDx9zOJ8A=
  file: poe-tool.exe
  on:
    repo: Ronmi/poe-tool
    tags: true

addons:
  apt:
    packages:
    - build-essential
    - libgtk-3-dev
    - libgtk2.0-dev
